### ISSUE TITLE
[Cata] Blizzard Options errors after 4.4.1

### ISSUE THREAD

**Issue by Road-block** [ToastyDev/GuildBankAudit#1]
Fix(es)
Replace client checks with API availability checks in a couple places.
`function SlashCmdList.GUILDBANKAUDIT(cmd, editbox)`
Replace the "options" bit with
```lua
  elseif request == "options" then
    if Settings and Settings.OpenToCategory then
      Settings.OpenToCategory(eventFrame.OptionsPanel.SettingsCategoryID)
    elseif _G.InterfaceOptionsFrame_OpenToCategory then
      InterfaceOptionsFrame_OpenToCategory(eventFrame.OptionsPanel)
    end
```
`function EventFrame:createOptionsPanel()`
Replace the client flavor check with
```lua
  --tww changes
  if Settings and Settings.RegisterCanvasLayoutCategory then
    local category = Settings.RegisterCanvasLayoutCategory(self.OptionsPanel, self.OptionsPanel.name)
    Settings.RegisterCategory(category)
    self.OptionsPanel.SettingsCategoryID = category:GetID()
  end
```
also replace the end bit in same function with
```lua
  if _G.InterfaceOptions_AddCategory then
    InterfaceOptions_AddCategory(self.OptionsPanel)
  end
```

Finally in `function createButtons()`
replace the client flavor check for the ExtendedMoney button with 
```lua
buttonFrame.ExtendedMoney:SetPoint("BOTTOMRIGHT", GuildBankFrame, -5, -15)
```
The `local CLASSIC_CLIENT` etc at the top can now be removed, it's not used anyplace.
The RETAIL_CLIENT can stay as it's still used for wowhead link choice.

Hope it helps.

**Comment by ToastyDev** [comment]
Thanks for the help here, much appreciated!
